### ISSUE TITLE
incorrect phone number

### ISSUE THREAD

**Issue by harimurtie** [thamma/tttc#5]
whats the format of the phone number? 
+(country code)(phone number)?

**Comment by thamma** [comment]
Currently, it is 00(countrycode)(number). But your version should be applicable as well. I will take care of this in a few minutes. Then, I will also fix the 2FA login.

**Comment by thamma** [comment]
@harimurtie, please test the 2FA if you can. I eventually was blocked by the telegram servers for too many retries.

**Comment by harimurtie** [comment]
i'm sorry , didnt read your reply. i still cant login to my tele account. i use +62(number) and 0062(number), neither are work.

**Comment by harimurtie** [comment]
but the strange part is i receive login code in my other telegram session, even tttc said incorrect phone number.

**Comment by thamma** [comment]
Incorrect phone number is displayed i little bit too genericly. I'm looking into this, reporting back to you with at least a more verbose error message.

**Comment by thamma** [comment]
Please feel free to contact me on telegram so we can investigate this issue better. See my github profile.

**Comment by thamma** [comment]
I added more verbose error message printing in f052c47 in the investigation branch. Please report back.

**Comment by grenzionky** [comment]
im getting this message even though i put in put in my phone number correctly 001XXXXXXXXXX (i know its correct cuz i get a message from telegram with a code). because i get this error message, im not able to put in my code
![image](https://user-images.githubusercontent.com/13357949/74068687-43ec4300-49ca-11ea-9467-30d7a6d07df1.png)

**Comment by thamma** [comment]
The branch I mentioned in my previous comment shows you the specific error message at hand. Can you please check it out and report back with more info so we can settle this issue?

**Comment by thamma** [comment]
@grenzionky please check out 296b6aa for now. I found a change in the API from a few months ago and now. Several things have renamed, which stopped the authorization from completing properly.
Please do report back if this issue is fixed now.
@harimurtie if this is any relevant to you, too, please test it as well.

**Comment by grenzionky** [comment]
> The branch I mentioned in my previous comment shows you the specific error message at hand. Can you please check it out and report back with more info so we can settle this issue?

```
An error occured: 'SentCode' object has no attribute 'phone_registered'Please enter your phone number: 
```

**Comment by grenzionky** [comment]
> @grenzionky please check out [296b6aa](https://github.com/thamma/tttc/commit/296b6aab5e616f298a8b38dcefbe61a08ba6aec8) for now. I found a change in the API from a few months ago and now. Several things have renamed, which stopped the authorization from completing properly.
> Please do report back if this issue is fixed now.
> @harimurtie if this is any relevant to you, too, please test it as well.

that worked!

**Comment by thamma** [comment]
Nice.
